"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import type { FormField } from "./types";

interface ExportModalProps {
  open: boolean;
  onClose: () => void;
  fields: FormField[];
  title: string;
}

function generateHtml(fields: FormField[], title: string): string {
  const formName = title || "form";
  const renderField = (f: FormField): string => {
    const lbl = f.label;
    const req = f.required ? " required" : "";
    const ph = f.placeholder ? ` placeholder="${f.placeholder}"` : "";
    const baseClass = "w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all";

    switch (f.type) {
      case "textarea":
        return `      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 mb-1">${lbl}${f.required ? " <span class=\"text-red-500\">*</span>" : ""}</label>
        <textarea class="${baseClass} resize-y" rows="4"${ph}${req}></textarea>
      </div>`;
      case "select":
        return `      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 mb-1">${lbl}${f.required ? " <span class=\"text-red-500\">*</span>" : ""}</label>
        <select class="${baseClass} bg-white"${req}>
          <option value="">${f.placeholder || "Select..."}</option>
${f.options.map((o) => `          <option value="${o}">${o}</option>`).join("\n")}
        </select>
      </div>`;
      case "checkbox":
        return `      <div class="mb-4 flex items-start">
        <input type="checkbox" id="${f.id}" class="mt-1 mr-2"${req} />
        <label for="${f.id}" class="text-sm text-gray-700">${lbl}${f.required ? " <span class=\"text-red-500\">*</span>" : ""}</label>
      </div>`;
      case "radio":
        return `      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 mb-1">${lbl}${f.required ? " <span class=\"text-red-500\">*</span>" : ""}</label>
${f.options.map((o) => `        <label class="flex items-center gap-2 mb-1 text-sm text-gray-700">
          <input type="radio" name="${f.id}" value="${o}"${req} /> ${o}
        </label>`).join("\n")}
      </div>`;
      case "date":
        return `      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 mb-1">${lbl}${f.required ? " <span class=\"text-red-500\">*</span>" : ""}</label>
        <input type="date" class="${baseClass}"${req} />
      </div>`;
      default:
        return `      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 mb-1">${lbl}${f.required ? " <span class=\"text-red-500\">*</span>" : ""}</label>
        <input type="${f.type}" class="${baseClass}"${ph}${req} />
      </div>`;
    }
  };

  return `<!-- Form generated by FormLabs -->
<form class="max-w-lg mx-auto p-6 bg-white rounded-xl shadow-sm border border-gray-200"${formName ? ` name="${formName}"` : ""}>
  <h2 class="text-xl font-semibold text-gray-900 mb-6">${title || "Untitled Form"}</h2>
${fields.map(renderField).join("\n")}
  <button type="submit" class="w-full bg-blue-600 text-white py-2.5 rounded-lg font-medium hover:bg-blue-700 transition-colors">
    Submit
  </button>
</form>`;
}

function generateReact(fields: FormField[], title: string): string {
  const formName = title.replace(/[^a-zA-Z0-9]/g, "") || "Form";
  const stateHooks = fields
    .filter((f) => f.type !== "checkbox" && f.type !== "radio")
    .map((f) => `  const [${f.id}, set${f.id.charAt(0).toUpperCase() + f.id.slice(1)}] = useState("${f.defaultValue || ""}");`);
  const checkboxHooks = fields
    .filter((f) => f.type === "checkbox")
    .map((f) => `  const [${f.id}, set${f.id.charAt(0).toUpperCase() + f.id.slice(1)}] = useState(false);`);
  const radioHooks = fields
    .filter((f) => f.type === "radio")
    .map((f) => `  const [${f.id}, set${f.id.charAt(0).toUpperCase() + f.id.slice(1)}] = useState("");`);

  const renderField = (f: FormField): string => {
    const lbl = f.label;
    const req = f.required;
    const stateName = f.id;
    const setter = `set${stateName.charAt(0).toUpperCase() + stateName.slice(1)}`;

    switch (f.type) {
      case "textarea":
        return `        <div className="mb-4">
          <label className="block text-sm font-medium text-gray-700 mb-1">${lbl}${req ? " <span className=\"text-red-500\">*</span>" : ""}</label>
          <textarea
            value={${stateName}}
            onChange={(e) => ${setter}(e.target.value)}
            placeholder="${f.placeholder || ""}"
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            rows={4}
            ${req ? "required" : ""}
          />
        </div>`;
      case "select":
        return `        <div className="mb-4">
          <label className="block text-sm font-medium text-gray-700 mb-1">${lbl}${req ? " <span className=\"text-red-500\">*</span>" : ""}</label>
          <select
            value={${stateName}}
            onChange={(e) => ${setter}(e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            ${req ? "required" : ""}
          >
            <option value="">${f.placeholder || "Select..."}</option>
${f.options.map((o) => `            <option value="${o}">${o}</option>`).join("\n")}
          </select>
        </div>`;
      case "checkbox":
        return `        <div className="mb-4 flex items-start">
          <input
            type="checkbox"
            id="${f.id}"
            checked={${stateName}}
            onChange={(e) => ${setter}(e.target.checked)}
            className="mt-1 mr-2"
            ${req ? "required" : ""}
          />
          <label htmlFor="${f.id}" className="text-sm text-gray-700">${lbl}${req ? " <span className=\"text-red-500\">*</span>" : ""}</label>
        </div>`;
      case "radio":
        return `        <div className="mb-4">
          <label className="block text-sm font-medium text-gray-700 mb-1">${lbl}${req ? " <span className=\"text-red-500\">*</span>" : ""}</label>
${f.options.map((o) => `          <label className="flex items-center gap-2 mb-1 text-sm text-gray-700">
            <input
              type="radio"
              name="${f.id}"
              value="${o}"
              checked={${stateName} === "${o}"}
              onChange={(e) => ${setter}(e.target.value)}
              ${req ? "required" : ""}
            />
            ${o}
          </label>`).join("\n")}
        </div>`;
      case "date":
        return `        <div className="mb-4">
          <label className="block text-sm font-medium text-gray-700 mb-1">${lbl}${req ? " <span className=\"text-red-500\">*</span>" : ""}</label>
          <input
            type="date"
            value={${stateName}}
            onChange={(e) => ${setter}(e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            ${req ? "required" : ""}
          />
        </div>`;
      default:
        return `        <div className="mb-4">
          <label className="block text-sm font-medium text-gray-700 mb-1">${lbl}${req ? " <span className=\"text-red-500\">*</span>" : ""}</label>
          <input
            type="${f.type}"
            value={${stateName}}
            onChange={(e) => ${setter}(e.target.value)}
            placeholder="${f.placeholder || ""}"
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            ${req ? "required" : ""}
          />
        </div>`;
    }
  };

  const allHooks = [...stateHooks, ...checkboxHooks, ...radioHooks];

  return `import { useState } from "react";

export default function ${formName}Form() {
${allHooks.join("\n")}

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Handle form submission
    console.log({${fields.map((f) => f.id).join(", ")}});
  };

  return (
    <form onSubmit={handleSubmit} className="max-w-lg mx-auto p-6 bg-white rounded-xl shadow-sm border border-gray-200">
      <h2 className="text-xl font-semibold text-gray-900 mb-6">${title || "Untitled Form"}</h2>
${fields.map(renderField).join("\n")}
      <button
        type="submit"
        className="w-full bg-blue-600 text-white py-2.5 rounded-lg font-medium hover:bg-blue-700 transition-colors"
      >
        Submit
      </button>
    </form>
  );
}`;
}

export default function ExportModal({ open, onClose, fields, title }: ExportModalProps) {
  const [tab, setTab] = useState<"html" | "react">("html");
  const [copied, setCopied] = useState(false);
  const [highlightedCode, setHighlightedCode] = useState("");

  const code = tab === "html" ? generateHtml(fields, title) : generateReact(fields, title);

  useEffect(() => {
    async function highlight() {
      try {
        const hljs = (await import("highlight.js")).default;
        const result = hljs.highlight(code, { language: "xml" });
        setHighlightedCode(result.value);
      } catch {
        setHighlightedCode(code.replace(/[<>&]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" }[c] || c)));
      }
    }
    highlight();
  }, [code]);

  const copyCode = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
          onClick={onClose}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 10 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 10 }}
            transition={{ duration: 0.2, ease: [0.16, 1, 0.3, 1] }}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-2xl max-h-[80vh] flex flex-col bg-[#1a1a2e] border border-white/[0.08] rounded-2xl overflow-hidden shadow-2xl"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-5 py-3.5 border-b border-white/[0.06]">
              <div className="flex items-center gap-3">
                <h3 className="text-sm font-semibold text-gray-200">Export Form</h3>
                <div className="flex bg-white/[0.04] rounded-lg p-0.5 border border-white/[0.06]">
                  <button
                    onClick={() => setTab("html")}
                    className={`px-3 py-1 text-[11px] font-medium rounded-md transition-all ${
                      tab === "html" ? "bg-accent/10 text-accent" : "text-gray-500 hover:text-gray-300"
                    }`}
                  >
                    HTML
                  </button>
                  <button
                    onClick={() => setTab("react")}
                    className={`px-3 py-1 text-[11px] font-medium rounded-md transition-all ${
                      tab === "react" ? "bg-accent/10 text-accent" : "text-gray-500 hover:text-gray-300"
                    }`}
                  >
                    React
                  </button>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={copyCode}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-medium bg-white/[0.06] hover:bg-white/[0.1] text-gray-300 rounded-lg transition-all"
                >
                  {copied ? (
                    <>
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                        <polyline points="20 6 9 17 4 12" />
                      </svg>
                      Copied
                    </>
                  ) : (
                    <>
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                        <rect x="9" y="9" width="13" height="13" rx="2" />
                        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                      </svg>
                      Copy
                    </>
                  )}
                </button>
                <button onClick={onClose} className="text-gray-600 hover:text-gray-300 transition-colors">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                </button>
              </div>
            </div>

            {/* Code display */}
            <div className="flex-1 overflow-y-auto p-4">
              <pre className="font-mono text-xs leading-[1.7] text-gray-300 whitespace-pre">
                <code dangerouslySetInnerHTML={{ __html: highlightedCode }} />
              </pre>
            </div>

            {/* Footer */}
            <div className="px-5 py-3 border-t border-white/[0.06] text-[10px] text-gray-600">
              {fields.length} field{fields.length !== 1 ? "s" : ""} · {code.split("\n").length} lines
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
